on:
  push:
    branches:
      - release

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Load manifest
        id: manifest
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: "src/manifest/chrome.json"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.manifest.outputs.version }}
          release_name: Release ${{ steps.manifest.outputs.version }}
          body_path: changelog.md
          draft: false
          prerelease: false
