on:
  workflow_dispatch

name: Test Publish

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Setup
        run: |
          npm ci
          sudo apt-get install jq zip
          mkdir -p release/chrome release/firefox
      
      - id: manifest
        run: echo "version=$(jq -r '.version' src/manifest/chrome.json)" >> $GITHUB_OUTPUT
        
      - name: Upload Mozilla Store
        run: |
          npx web-ext-submit \
            --source-dir ./dist/firefox/
            --artifacts-dir ./release/firefox/
            --api-key=${{ secrets.WEB_EXT_API_KEY }} \
            --api-secret=${{ secrets.WEB_EXT_API_SECRET }}