name: Upload Chrome Extension

on: workflow_dispatch

jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |-
          npm install
          npm run build
          zip -r chrome-extension-${{ github.event.pull_request.head.sha }}.zip dist
      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.event.pull_request.head.sha }}.zip
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-latest
    needs: build-chrome-extension
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.10"
      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}
      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli
      - name: Upload step
        run: |-
          chrome-webstore-upload upload \\
            --source chrome-extension-${{ github.event.pull_request.head.sha }}.zip \\
            --extension-id ${{ secrets.EXTENSION_ID }} \\
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \\
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \\
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}